// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzc-Ur8j6WJ_IA365HwJg4JCERQRNEyso',
    appId: '1:973282617552:web:b81867ba8c147c957556d5',
    messagingSenderId: '973282617552',
    projectId: 'aispeechcoach-c5b63',
    authDomain: 'aispeechcoach-c5b63.firebaseapp.com',
    storageBucket: 'aispeechcoach-c5b63.firebasestorage.app',
    measurementId: 'G-MW2YZMBM5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTWZgRphrFllhs7fpk5LgO2moLCN1GRJM',
    appId: '1:973282617552:android:ed796d55311aee0c7556d5',
    messagingSenderId: '973282617552',
    projectId: 'aispeechcoach-c5b63',
    storageBucket: 'aispeechcoach-c5b63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCst5DG5ukSijQ5DYxElcGL23GCiwcmjlg',
    appId: '1:973282617552:ios:c356bb0b41021fbe7556d5',
    messagingSenderId: '973282617552',
    projectId: 'aispeechcoach-c5b63',
    storageBucket: 'aispeechcoach-c5b63.firebasestorage.app',
    iosBundleId: 'com.example.aispeechcoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCst5DG5ukSijQ5DYxElcGL23GCiwcmjlg',
    appId: '1:973282617552:ios:c356bb0b41021fbe7556d5',
    messagingSenderId: '973282617552',
    projectId: 'aispeechcoach-c5b63',
    storageBucket: 'aispeechcoach-c5b63.firebasestorage.app',
    iosBundleId: 'com.example.aispeechcoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzc-Ur8j6WJ_IA365HwJg4JCERQRNEyso',
    appId: '1:973282617552:web:3408419f529ac6357556d5',
    messagingSenderId: '973282617552',
    projectId: 'aispeechcoach-c5b63',
    authDomain: 'aispeechcoach-c5b63.firebaseapp.com',
    storageBucket: 'aispeechcoach-c5b63.firebasestorage.app',
    measurementId: 'G-T78FL74ZEY',
  );
}
