import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Login(),
        ]),
      ),
    );
  }
}

class Login extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 61,
                top: 765,
                child: Text.rich(
                  TextSpan(
                    children: [
                      TextSpan(
                        text: 'Don’t have an account? ',
                        style: TextStyle(
                          color: const Color(0xFF24282C),
                          fontSize: 15,
                          fontFamily: 'Urbanist',
                          fontWeight: FontWeight.w500,
                          height: 1.40,
                          letterSpacing: 0.15,
                        ),
                      ),
                      TextSpan(
                        text: 'Register Now',
                        style: TextStyle(
                          color: const Color(0xFF34C2C1),
                          fontSize: 15,
                          fontFamily: 'Urbanist',
                          fontWeight: FontWeight.w700,
                          height: 1.40,
                          letterSpacing: 0.15,
                        ),
                      ),
                    ],
                  ),
                  textAlign: TextAlign.center,
                ),
              ),
              Positioned(
                left: 142,
                top: 557,
                child: Container(
                  width: 105,
                  height: 56,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFE8ECF4),
                      ),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 179,
                top: 572,
                child: Container(
                  width: 26,
                  height: 26,
                  alignment: Alignment.center,
                  child: SvgPicture.asset(
                    'icons/google_ic.svg',
                    width: 24,
                    height: 24,
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 557,
                child: Container(
                  width: 105,
                  height: 56,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFE8ECF4),
                      ),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 66,
                top: 572,
                child: Container(
                  width: 26,
                  height: 26,
                  alignment: Alignment.center,
                  child: FaIcon(
                    FontAwesomeIcons.facebookF,
                    size: 24,
                    color: Color(0xFF1877F2),
                  ),
                ),
              ),
              Positioned(
                left: 255,
                top: 557,
                child: Container(
                  width: 105,
                  height: 56,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFE8ECF4),
                      ),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 292,
                top: 572,
                child: Container(
                  width: 26,
                  height: 26,
                  alignment: Alignment.center,
                  child: FaIcon(
                    FontAwesomeIcons.apple,
                    size: 26,
                    color: Colors.black,
                  ),
                ),
              ),
              Positioned(
                left: 153,
                top: 518,
                child: Text(
                  'Or Login with',
                  style: TextStyle(
                    color: const Color(0xFF6A707C),
                    fontSize: 14,
                    fontFamily: 'Urbanist',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 527,
                child: Container(
                  width: 112,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFFE8ECF4),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 249,
                top: 527,
                child: Container(
                  width: 111,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFFE8ECF4),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 22.88,
                top: 424.71,
                child: PressableButton(
                  width: 344.24,
                  height: 58.21,
                  borderRadius: BorderRadius.circular(8),
                  splashColor: Colors.white.withOpacity(0.1), // 검은 버튼이라 흰색 물결 효과
                  onTap: () {
                    debugPrint("Login Button Tapped"); // 클릭 시 동작
                  },
                  child: Container(
                    alignment: Alignment.center, // 텍스트 중앙 정렬
                    decoration: ShapeDecoration(
                      color: const Color(0xFF1E232C),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                    ),
                    child: Text(
                      'Login',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 15,
                        fontFamily: 'Urbanist',
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 242,
                top: 377,
                child: Text(
                  'Forgot Password?',
                  textAlign: TextAlign.right,
                  style: TextStyle(
                    color: const Color(0xFF6A707C),
                    fontSize: 14,
                    fontFamily: 'Urbanist',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 306,
                child: Container(
                  width: 331,
                  height: 56,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFF6F7F8),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFE8ECF4),
                      ),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 319,
                top: 323,
                child: Container(
                  width: 22,
                  height: 22,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 44,
                top: 324,
                child: Text(
                  'Enter your password',
                  style: TextStyle(
                    color: const Color(0xFF8390A1),
                    fontSize: 15,
                    fontFamily: 'Urbanist',
                    fontWeight: FontWeight.w500,
                    height: 1.25,
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 235,
                child: Container(
                  width: 331,
                  height: 56,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFF7F8F9),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFE8ECF4),
                      ),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 253,
                child: Text(
                  'Enter your email',
                  style: TextStyle(
                    color: const Color(0xFF8390A1),
                    fontSize: 15,
                    fontFamily: 'Urbanist',
                    fontWeight: FontWeight.w500,
                    height: 1.25,
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 128,
                child: SizedBox(
                  width: 315,
                  child: Text(
                    '다시 만나서 반가워요!',
                    style: TextStyle(
                      color: const Color(0xFF1E232C),
                      fontSize: 32,
                      fontFamily: 'Urbanist',
                      fontWeight: FontWeight.w700,
                      height: 1.30,
                      letterSpacing: -0.32,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 170,
                child: SizedBox(
                  width: 300,
                  child: Text(
                    '오늘도 멋진 스피치를 위해 함께해요.',
                    style: TextStyle(
                      color: const Color(0xFF1E232C),
                      fontSize: 20,
                      fontFamily: 'Urbanist',
                      fontWeight: FontWeight.w500,
                      height: 1.30,
                      letterSpacing: -0.20,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 56,
                child: Container(
                  width: 41,
                  height: 41,
                  decoration: ShapeDecoration(
                    color: Colors.white,
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFE8ECF4),
                      ),
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 33.28,
                top: 69.64,
                child: Container(
                  width: 20,
                  height: 20,
                  alignment: Alignment.center,
                  child: GestureDetector(
                    onTap: () {
                      Navigator.pop(context);
                    },
                    child: FaIcon(
                      Icons.arrow_back_ios,
                      size: 20,
                      color: Color(0xFF1E232C),
                    ),
                  )
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

// PressableButton: 누를 때 scale 애니메이션과 InkWell 잉크 효과 제공
class PressableButton extends StatefulWidget {
  final Widget child;
  final VoidCallback? onTap;
  final double? width;
  final double? height;
  final BorderRadius? borderRadius;
  final Color? splashColor;
  final Duration duration;

  const PressableButton({
    super.key,
    required this.child,
    this.onTap,
    this.width,
    this.height,
    this.borderRadius,
    this.splashColor,
    this.duration = const Duration(milliseconds: 80),
  });

  @override
  State<PressableButton> createState() => _PressableButtonState();
}

class _PressableButtonState extends State<PressableButton> {
  bool _pressed = false;

  void _setPressed(bool value) {
    if (mounted) {
      setState(() {
        _pressed = value;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.transparent,
      child: AnimatedScale(
        scale: _pressed ? 0.98 : 1.0,
        duration: widget.duration,
        curve: Curves.easeOut,
        child: Ink(
          width: widget.width,
          height: widget.height,
          decoration: BoxDecoration(
            borderRadius: widget.borderRadius ?? BorderRadius.zero,
          ),
          child: InkWell(
            borderRadius: widget.borderRadius,
            splashColor: widget.splashColor,
            onTap: widget.onTap,
            onTapDown: (_) => _setPressed(true),
            onTapUp: (_) => _setPressed(false),
            onTapCancel: () => _setPressed(false),
            child: widget.child,
          ),
        ),
      ),
    );
  }
}