import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Welcome(),
        ]),
      ),
    );
  }
}

class Welcome extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.50, -0.00),
              end: Alignment(0.50, 1.00),
              colors: [Colors.white, Colors.white],
            ),
            boxShadow: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 20,
                offset: Offset(0, 8),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: -85,
                top: 32,
                child: Opacity(
                  opacity: 0.08,
                  child: Container(
                    width: 236,
                    height: 236,
                    decoration: ShapeDecoration(
                      color: const Color(0xFF9ED9FF),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 265,
                top: 429,
                child: Opacity(
                  opacity: 0.08,
                  child: Container(
                    width: 236,
                    height: 236,
                    decoration: ShapeDecoration(
                      color: const Color(0xFF9ED9FF),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 390,
                  height: 844,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/390x844"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 128,
                top: 783,
                child: Text(
                  'Continue as a guest',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFF42A5F5),
                    fontSize: 15,
                    fontFamily: 'Urbanist',
                    fontWeight: FontWeight.w700,
                    decoration: TextDecoration.underline,
                  ),
                ),
              ),

              // Register button (white background with border) - PressableButton 사용
              Positioned(
                left: 22.88,
                top: 706.80,
                child: PressableButton(
                  width: 344.24,
                  height: 58.21,
                  borderRadius: BorderRadius.circular(8),
                  splashColor: Colors.black12,
                  onTap: () {
                    debugPrint('Register tapped');
                  },
                  child: Container(
                    alignment: Alignment.center,
                    decoration: ShapeDecoration(
                      color: Colors.white,
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          color: const Color(0xFF1E232C),
                        ),
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                    child: Text(
                      'Register',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: const Color(0xFF1E232C),
                        fontSize: 15,
                        fontFamily: 'Urbanist',
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                ),
              ),

              // Login button (dark background) - PressableButton 사용
              Positioned(
                left: 22.88,
                top: 633,
                child: PressableButton(
                  width: 344.24,
                  height: 58.21,
                  borderRadius: BorderRadius.circular(8),
                  splashColor: Colors.white24,
                  onTap: () {
                    debugPrint('Login tapped');
                  },
                  child: Container(
                    alignment: Alignment.center,
                    decoration: ShapeDecoration(
                      color: const Color(0xFF1E232C),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                    child: Text(
                      'Login',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 15,
                        fontFamily: 'Urbanist',
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                ),
              ),

              Positioned(
                left: 102,
                top: 381,
                child: Text(
                  'AI Speech Coach',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 24,
                    fontFamily: 'Urbanist',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 154,
                top: 277,
                child: Container(
                  width: 81,
                  height: 82,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: AssetImage("images/MainLogo.png"),
                      fit: BoxFit.contain,
                      filterQuality: FilterQuality.high,
                    ),
                    shape: OvalBorder(),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 8,
                        offset: Offset(0, 2),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 84,
                top: 484,
                child: Text(
                  'AI와 함께, 당신의 목소리에                   자신감을 더하세요.',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 20,
                    fontFamily: 'Urbanist',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
              Positioned(
                left: 78,
                top: 541,
                child: Text(
                  '언제나 어디서나, 당신만을 위한 스피치 코치',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFFB5B0B0),
                    fontSize: 13,
                    fontFamily: 'Urbanist',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

// PressableButton: 누를 때 scale 애니메이션과 InkWell 잉크 효과 제공
class PressableButton extends StatefulWidget {
  final Widget child;
  final VoidCallback? onTap;
  final double? width;
  final double? height;
  final BorderRadius? borderRadius;
  final Color? splashColor;
  final Duration duration;

  const PressableButton({
    super.key,
    required this.child,
    this.onTap,
    this.width,
    this.height,
    this.borderRadius,
    this.splashColor,
    this.duration = const Duration(milliseconds: 80),
  });

  @override
  State<PressableButton> createState() => _PressableButtonState();
}

class _PressableButtonState extends State<PressableButton> {
  bool _pressed = false;

  void _setPressed(bool value) {
    if (mounted) {
      setState(() {
        _pressed = value;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.transparent,
      child: AnimatedScale(
        scale: _pressed ? 0.98 : 1.0,
        duration: widget.duration,
        curve: Curves.easeOut,
        child: Ink(
          width: widget.width,
          height: widget.height,
          decoration: BoxDecoration(
            borderRadius: widget.borderRadius ?? BorderRadius.zero,
          ),
          child: InkWell(
            borderRadius: widget.borderRadius,
            splashColor: widget.splashColor,
            onTap: widget.onTap,
            onTapDown: (_) => _setPressed(true),
            onTapUp: (_) => _setPressed(false),
            onTapCancel: () => _setPressed(false),
            child: widget.child,
          ),
        ),
      ),
    );
  }
}
