import 'package:aispeechcoach/firebase_options.dart';
import 'package:aispeechcoach/main_tab_screen.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'pressable_button.dart';
import 'login.dart'; // 로그인 화면 파일
import 'register.dart'; // 회원가입 화면 파일
import 'home_screen_1.dart';

void main() async {
  // main 함수를 async로 변경
  WidgetsFlutterBinding.ensureInitialized(); // Flutter 엔진 초기화 보장
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // firebase_options.dart 임포트 후 주석 해제
  );
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.light().copyWith( // 테마를 라이트 모드로 변경 (흰색 배경이므로)
        scaffoldBackgroundColor: Colors.white,
      ),
      home: Scaffold(
        body: ListView(children: [
          Welcome(),
        ]),
      ),
    );
  }
}

class Welcome extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(
            gradient: LinearGradient(
              begin: Alignment(0.50, -0.00),
              end: Alignment(0.50, 1.00),
              colors: [Colors.white, Colors.white],
            ),
            boxShadow: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 20,
                offset: Offset(0, 8),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: -85,
                top: 32,
                child: Opacity(
                  opacity: 0.08,
                  child: Container(
                    width: 236,
                    height: 236,
                    decoration: ShapeDecoration(
                      color: const Color(0xFF9ED9FF),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 265,
                top: 429,
                child: Opacity(
                  opacity: 0.08,
                  child: Container(
                    width: 236,
                    height: 236,
                    decoration: ShapeDecoration(
                      color: const Color(0xFF9ED9FF),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 390,
                  height: 844,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/390x844"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 128,
                top: 783,
                child: GestureDetector( // 클릭 가능하도록 GestureDetector 추가
                  onTap: () {
                    debugPrint('Continue as a guest tapped');
                    // TODO: 게스트로 계속하기 로직 (예: 홈 화면으로 이동)
                    Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) => MainTabScreen()));
                  },
                  child: Text(
                    'Continue as a guest',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF42A5F5),
                      fontSize: 15,
                      fontFamily: 'Urbanist',
                      fontWeight: FontWeight.w700,
                      decoration: TextDecoration.underline,
                      decorationColor: const Color(0xFF42A5F5), // 밑줄 색상 추가
                    ),
                  ),
                ),
              ),

              // Register button (white background with border) - PressableButton 사용
              Positioned(
                left: 22.88,
                top: 706.80,
                child: PressableButton(
                  width: 344.24,
                  height: 58.21,
                  borderRadius: BorderRadius.circular(8),
                  splashColor: Colors.black12,
                  onTap: () {
                    // <<< 수정됨: Register 화면으로 이동
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => Register()), // Register()는 register.dart의 위젯
                    );
                  },
                  child: Container(
                    alignment: Alignment.center,
                    decoration: ShapeDecoration(
                      color: Colors.white,
                      shape: RoundedRectangleBorder(
                        side: BorderSide(
                          width: 1,
                          color: const Color(0xFF1E232C),
                        ),
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                    child: Text(
                      'Register',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: const Color(0xFF1E232C),
                        fontSize: 15,
                        fontFamily: 'Urbanist',
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                ),
              ),

              // Login button (dark background) - PressableButton 사용
              Positioned(
                left: 22.88,
                top: 633,
                child: PressableButton(
                  width: 344.24,
                  height: 58.21,
                  borderRadius: BorderRadius.circular(8),
                  splashColor: Colors.white24,
                  onTap: () {
                    // <<< 수정됨: Login 화면으로 이동
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => Login()), // Login()은 login.dart의 위젯
                    );
                  },
                  child: Container(
                    alignment: Alignment.center,
                    decoration: ShapeDecoration(
                      color: const Color(0xFF1E232C),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(8),
                      ),
                    ),
                    child: Text(
                      'Login',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        color: Colors.white,
                        fontSize: 15,
                        fontFamily: 'Urbanist',
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                ),
              ),

              Positioned(
                left: 102,
                top: 381,
                child: Text(
                  'AI Speech Coach',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 24,
                    fontFamily: 'Urbanist',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 154,
                top: 277,
                child: Container(
                  width: 81,
                  height: 82,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: AssetImage("images/MainLogo2.png"), // 경로는 pubspec.yaml 기준입니다.
                      fit: BoxFit.contain,
                      filterQuality: FilterQuality.high,
                    ),
                    shape: OvalBorder(),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 8,
                        offset: Offset(0, 2),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                right: 0,
                top: 484,
                child: Text(
                  'AI와 함께, 당신의 목소리에\n자신감을 더하세요.',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 20,
                    fontFamily: 'Urbanist',
                    fontWeight: FontWeight.w600,
                  ),
                ),
              ),
              Positioned(
                left: 0, // 가운데 정렬을 위해 left, right 0으로
                right: 0,
                top: 541,
                child: Text(
                  '언제나 어디서나, 당신만을 위한 스피치 코치',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFFB5B0B0),
                    fontSize: 13,
                    fontFamily: 'Urbanist',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}